### PR TITLE
feat: added timer

### PR DESCRIPTION
**Pull request by nikhilverma360**
Added Timer

| Player QR Timer | Question Timer |
|---------|---------|
| Player QR Timer | Question Timer |

### CODE REVIEW

**Comment by nikhilverma360** [comment]
Should we increase size of  "Schelling Question" header in Question page?

**Review by alcercu — CHANGES_REQUESTED** [review]
I would prefer if the values that are added to the timestamps to get the expiry were set with an env variable or a global const

**Comment by nikhilverma360** [comment]
should we add it to game.config.ts

**Review by alcercu — APPROVED** [review]
lgtm

**Pull request merged**
